# Generated by Django 6.0.5 on 2026-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
