# Generated by Django 6.0.5 on 2026-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_avatar_frame_customuser_contracts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='challenge_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_challenges_generated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
