# Generated by Django 6.0.5 on 2026-06-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_challenge_history_customuser_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_avatar_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ai_name',
            field=models.CharField(blank=True, default='ChillX', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ai_personality',
            field=models.TextField(blank=True, default='', help_text='Memory & personalization details for your AI companion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-1.5-flash', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groq_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groq_model',
            field=models.CharField(blank=True, default='llama-3.3-70b-versatile', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='openrouter_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='openrouter_model',
            field=models.CharField(blank=True, default='openai/gpt-4o-mini', max_length=100),
        ),
    ]
