# Generated by Django 6.0.5 on 2026-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_ai_avatar_base64_customuser_ai_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_free_reroll_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
