# Generated by Django 6.0.5 on 2026-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_last_free_reroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic_generations',
            field=models.IntegerField(default=0),
        ),
    ]
