# Generated by Django 6.0.5 on 2026-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_profile_pic_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
    ]
