# Generated by Django 6.0.5 on 2026-06-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_diamonds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='flex_effect',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
