# Generated by Django 6.0.5 on 2026-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_custom_title_customuser_flex_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_border',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bg_effect',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name_effect',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
