from django.urls import path
from . import views
from . import shop_views
from . import achievement_views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('shop/', views.shop_page, name='shop'),
    path('inventory/', views.inventory_view, name='inventory'),
    path('chillx/', views.chillx_view, name='chillx'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('onboarding/', views.onboarding_view, name='onboarding'),
    path('create-profile/', views.create_profile_view, name='create_profile'),
    path('signup/', views.signup_view, name='signup'),
    path('signin/', views.signin_view, name='signin'),
    path('logout/', views.logout_view, name='logout'),
    path('settings/', views.settings_view, name='settings'),
    path('challenges/', views.challenges_view, name='challenges'),
    path('challenges/submit/<int:challenge_id>/', views.challenge_submit, name='challenge_submit'),
    path('challenges/regenerate/<int:challenge_id>/', views.challenge_regenerate, name='challenge_regenerate'),
    path('challenges/generate-more/', views.challenge_generate_more, name='challenge_generate_more'),
    path('challenges/delete/<int:challenge_id>/', views.challenge_delete, name='challenge_delete'),
    path('challenges/delete-bulk/', views.challenge_delete_bulk, name='challenge_delete_bulk'),
    path('challenges/generate-sse/', views.challenge_generate_sse, name='challenge_generate_sse'),
    path('challenges/chat/', views.challenge_chat, name='challenge_chat'),
    path('challenges/verify-cps/', views.verify_cps, name='verify_cps'),
    path('challenges/verify-reaction/', views.verify_reaction, name='verify_reaction'),
    path('challenges/verify-typing/', views.verify_typing, name='verify_typing'),
    path('challenges/verify-memory/', views.verify_memory, name='verify_memory'),
    path('challenges/verify-runner/', views.verify_runner, name='verify_runner'),
    path('challenges/verify-tictactoe/', views.verify_tictactoe, name='verify_tictactoe'),
    path('challenges/verify-aim3d/', views.verify_aim3d, name='verify_aim3d'),
    path('challenges/verify-fitness/', views.verify_fitness, name='verify_fitness'),
    path('challenges/verify-quiz/', views.verify_quiz, name='verify_quiz'),
    path('fitness/analyze/', views.fitness_analyze, name='fitness_analyze'),
    path('quiz/generate-questions/', views.quiz_generate_questions, name='quiz_generate_questions'),
    # In-house mini-games
    path('games/<slug:game_name>/', views.game_view, name='game'),
    path('multiplayer-game/<slug:game_name>/', views.multiplayer_game_view, name='multiplayer_game'),
    path('api/user-stats/', views.user_stats_json, name='user_stats_json'),

    # Shop API
    path('api/shop/items/', shop_views.shop_items, name='shop_items'),
    path('api/shop/items/featured/', shop_views.shop_featured, name='shop_featured'),
    path('api/shop/buy/', shop_views.shop_buy, name='shop_buy'),
    path('api/shop/inventory/', shop_views.shop_inventory, name='shop_inventory'),
    path('api/shop/wallet/', shop_views.shop_wallet, name='shop_wallet'),
    path('api/shop/avatar/', shop_views.avatar_image, name='avatar_image'),
    path('api/shop/raffle/current/', shop_views.raffle_current, name='raffle_current'),
    path('api/shop/raffle/buy/', shop_views.raffle_buy, name='raffle_buy'),
    path('api/shop/recent/', shop_views.recent_purchases, name='recent_purchases'),
    path('api/shop/crate/open/', shop_views.crate_open, name='crate_open'),
    path('api/shop/inventory/toggle/', shop_views.inventory_toggle, name='inventory_toggle'),
    path('api/shop/ai-profile/', shop_views.ai_profile_pic, name='ai_profile_pic'),
    path('api/shop/avatar-upload/', shop_views.avatar_upload, name='avatar_upload'),
    path('api/shop/promo/redeem/', shop_views.redeem_promo, name='redeem_promo'),
    path('api/shop/custom-title/', shop_views.custom_title_create, name='custom_title_create'),

    # Achievement API
    path('api/achievements/', achievement_views.achievement_list, name='achievement_list'),
    path('api/achievements/titles/', achievement_views.title_list, name='title_list'),
    path('api/achievements/equip-title/', achievement_views.equip_title, name='equip_title'),
    path('api/achievements/progress/', achievement_views.update_achievement_progress, name='update_achievement_progress'),
    path('api/user/xp/', achievement_views.user_xp_status, name='user_xp_status'),
    path('api/user/deduct-coins/', achievement_views.deduct_coins, name='deduct_coins'),
    path('achievements/', views.achievement_page, name='achievements'),
    path('api/game/save-stats/', views.save_game_stats, name='save_game_stats'),

    # Social / ChillX Posts
    path('social/', views.social_view, name='social'),
    path('social/create/', views.social_create_post, name='social_create_post'),
    path('social/<int:post_id>/vote/', views.social_vote, name='social_vote'),
    path('social/<int:post_id>/comment/', views.social_comment, name='social_comment'),
    path('social/<int:post_id>/delete/', views.social_delete_post, name='social_delete_post'),
    path('social/live/', views.social_live, name='social_live'),
    path('social/share/<int:challenge_id>/', views.social_share, name='social_share'),
    path('social/follow/<int:user_id>/', views.toggle_follow, name='toggle_follow'),
    path('social/friends/search/', views.search_users_api, name='search_users'),
    path('social/friends/request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('social/friends/respond/<int:request_id>/', views.respond_friend_request, name='respond_friend_request'),
    path('social/friends/list/', views.list_friends_api, name='list_friends'),
    path('social/friends/pending/', views.list_pending_api, name='list_pending'),
    path('social/friends/unfriend/<int:user_id>/', views.unfriend_api, name='unfriend'),
    path('social/stories/', views.get_stories, name='get_stories'),
    path('social/stories/create/', views.create_story, name='create_story'),
    path('social/stories/<int:story_id>/delete/', views.delete_story, name='delete_story'),
    path('social/stories/<int:story_id>/react/', views.react_to_story, name='react_to_story'),
    path('social/stories/<int:story_id>/reply/', views.reply_to_story, name='reply_to_story'),
    path('social/profile/<int:user_id>/', views.social_profile_view, name='social_profile'),
    path('social/profile/by-username/<str:username>/', views.social_profile_by_username, name='social_profile_by_username'),

    # ChatX
    path('chatx/', views.chatx_view, name='chatx'),
    path('chatx/send/', views.send_message, name='send_message'),
    path('chatx/messages/<int:user_id>/', views.get_messages, name='get_messages'),
    path('chatx/conversations/', views.get_conversations, name='get_conversations'),
    path('chatx/edit/', views.edit_message, name='edit_message'),
    path('chatx/delete/', views.delete_message, name='delete_message'),
    path('chatx/users/', views.chat_users, name='chat_users'),
    path('chatx/call/signal/<int:user_id>/', views.send_call_signal, name='send_call_signal'),
    path('chatx/call/poll/', views.poll_call_signals, name='poll_call_signals'),
    path('chatx/call/status/<int:user_id>/', views.call_status, name='call_status'),

    # Multiplayer
    path('multiplayer/', views.multiplayer_view, name='multiplayer'),
    path('multiplayer/create/', views.multiplayer_create_room, name='multiplayer_create'),
    path('multiplayer/join/', views.multiplayer_join_room, name='multiplayer_join'),
    path('multiplayer/room/<str:room_code>/', views.multiplayer_room_state, name='multiplayer_room_state'),
    path('multiplayer/chat/send/', views.multiplayer_chat_send, name='multiplayer_chat_send'),
    path('multiplayer/chat/poll/', views.multiplayer_chat_poll, name='multiplayer_chat_poll'),
]
