# Generated by Django 6.0.5 on 2026-06-01 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=50)),
                ('coin_reward', models.IntegerField(default=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('nightmare', 'Nightmare')], default='medium', max_length=20)),
                ('proof_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('both', 'Both')], default='text', max_length=10)),
                ('is_long', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('proof_text', models.TextField(blank=True)),
                ('proof_image', models.TextField(blank=True)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('ai_checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'category'],
            },
        ),
    ]
