# Generated by Django 6.0.5 on 2026-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
