# Generated by Django 6.0.5 on 2026-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_challenge_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='game_key',
            field=models.CharField(blank=True, default='', help_text='In-app game this challenge links to (typing, reaction, cps, aim3d, memory, tictactoe, runner)', max_length=30),
        ),
    ]
