# Generated by Django 6.0.5 on 2026-06-06 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_challenge_game_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=30)),
                ('best_score', models.IntegerField(default=0)),
                ('best_score_secondary', models.IntegerField(default=0, help_text='Second metric (e.g. accuracy for typing)')),
                ('plays', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
