# Generated by Django 6.0.5 on 2026-06-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_achievement_title_userachievement_usertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamestats',
            name='deaths',
            field=models.IntegerField(default=0, help_text='Total deaths across all sessions (e.g. runner game)'),
        ),
        migrations.AddField(
            model_name='usergamestats',
            name='losses',
            field=models.IntegerField(default=0, help_text='Multiplayer arena losses for this game'),
        ),
        migrations.AddField(
            model_name='usergamestats',
            name='wins',
            field=models.IntegerField(default=0, help_text='Multiplayer arena wins for this game'),
        ),
    ]
