# Generated by Django 6.0.5 on 2026-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_add_game_stats_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ai_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Raw validated AI payload for auditing'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='estimated_duration',
            field=models.CharField(blank=True, default='', help_text='Rough effort, e.g. "3 minutes"', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='metric',
            field=models.CharField(blank=True, default='', help_text='Measured metric, e.g. wpm, accuracy, cps, ms, score', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='objective',
            field=models.CharField(blank=True, default='', help_text='Structured objective, e.g. "reach the target"', max_length=200),
        ),
        migrations.AddField(
            model_name='challenge',
            name='special_condition',
            field=models.TextField(blank=True, default='', help_text='Optional mechanic/special condition'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='target',
            field=models.FloatField(blank=True, help_text='Numeric target for the metric', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit for the target, e.g. wpm, %, seconds, reps', max_length=20),
        ),
    ]
